web-app/Models/Relay.cs
namespace PiWebApp.Models
{
    public enum Relay
    {
        Relay1,
        Relay2,
        Relay3
    }
}

web-app/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace PiWebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

web-app/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.SignalR;
using PiWebApp.Models;

namespace PiWebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IIoController _ioController;
        private readonly IHubContext<SignalRHub, ISignalRHub> _hubContext;
        private readonly ILogger<IndexModel> _logger;

        public bool ButtonPressed { get; private set; }

        public IndexModel(IIoController ioController, IHubContext<SignalRHub, ISignalRHub> hubContext, ILogger<IndexModel> logger)
        {
            _ioController = ioController;
            _hubContext = hubContext;
            _logger = logger;

            _ioController.ButtonPressed += OnButtonPressed;
            _ioController.ButtonReleased += OnButtonReleased;
        }

        public void OnGet()
        {
            ButtonPressed = _ioController.IsButtonPressed;
            _logger.LogInformation($"Current button state is {(ButtonPressed ? "pressed" : "released")}");
        }

        public void OnPostRelay(int relay, bool on)
        {
            _logger.LogInformation($"Setting relay {relay} {(on ? "on" : "off")}");
            _ioController.SetRelayState((Relay)relay, on);
        }

        public void OnPostLed(bool on)
        {
            _logger.LogInformation($"Setting LED {(on ? "on" : "off")}");
            _ioController.SetLedState(on);
        }


        private void OnButtonPressed(object? sender, EventArgs e)
        {
            _logger.LogInformation("Button is pressed. Sending SignalR message.");
            _hubContext.Clients.All.SendButtonState(true);
        }

        private void OnButtonReleased(object? sender, EventArgs e)
        {
            _logger.LogInformation("Button is released. Sending SignalR message.");
            _hubContext.Clients.All.SendButtonState(false);
        }
    }
}

web-app/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <p>This web application assumes that an RPi relay board is mounted on the Raspberry Pi</p>
    <img src="images/RPi-relay-board-mounted.jpg" />
</div>

<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Relay 1</h4>
            </div>
            <div class="card-body">
                <form method="post" asp-page-handler="relay">
                    <button type="submit" class="w-100 btn btn-lg btn-primary">ON</button>
                    <input type="hidden" name="on" value="true" />
                    <input type="hidden" name="relay" value="0" />
                </form>
                <p></p>
                <form method="post" asp-page-handler="relay">
                    <button type="submit" class="w-100 btn btn-lg btn-secondary">OFF</button>
                    <input type="hidden" name="on" value="false" />
                    <input type="hidden" name="relay" value="0" />
                </form>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Relay 2</h4>
            </div>
            <div class="card-body">
                <form method="post" asp-page-handler="relay">
                    <button type="submit" class="w-100 btn btn-lg btn-primary">ON</button>
                    <input type="hidden" name="on" value="true" />
                    <input type="hidden" name="relay" value="1" />
                </form>
                <p></p>
                <form method="post" asp-page-handler="relay">
                    <button type="submit" class="w-100 btn btn-lg btn-secondary">OFF</button>
                    <input type="hidden" name="on" value="false" />
                    <input type="hidden" name="relay" value="1" />
                </form>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Relay 3</h4>
            </div>
            <div class="card-body">
                <form method="post" asp-page-handler="relay">
                    <button type="submit" class="w-100 btn btn-lg btn-primary">ON</button>
                    <input type="hidden" name="on" value="true" />
                    <input type="hidden" name="relay" value="2" />
                </form>
                <p></p>
                <form method="post" asp-page-handler="relay">
                    <button type="submit" class="w-100 btn btn-lg btn-secondary">OFF</button>
                    <input type="hidden" name="on" value="false" />
                    <input type="hidden" name="relay" value="2" />
                </form>
            </div>
        </div>
    </div>
</div>
<p></p>
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Green LED</h4>
            </div>
            <div class="card-body">
                <form method="post" asp-page-handler="led">
                    <button type="submit" class="w-100 btn btn-lg btn-primary">ON</button>
                    <input type="hidden" name="on" value="true" />
                </form>
                <p></p>
                <form method="post" asp-page-handler="led">
                    <button type="submit" class="w-100 btn btn-lg btn-secondary">OFF</button>
                    <input type="hidden" name="on" value="false" />
                </form>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Button</h4>
            </div>
            <div class="card-body" id="buttonState">
                @if (Model.ButtonPressed)
                {
                    <p>Button is pressed</p>
                }
                else
                {
                    <p>Button is not pressed</p>
                }
            </div>
        </div>
    </div>
</div>

<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/buttonstate.js"></script>

web-app/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pi Web App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PiWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Raspberry Pi I/O Controller</a>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>